-- Normalize common legacy category values to the canonical Italian labels
-- used by the fixed catalog. This script is intentionally conservative:
-- it updates only well-known aliases and leaves the rest untouched so the
-- application can still render them through legacy fallback handling.

update public.transactions
set category = case lower(trim(category))
  when 'spesa' then 'Spesa alimentare'
  when 'alimentari' then 'Spesa alimentare'
  when 'supermercato' then 'Spesa alimentare'
  when 'spesa alimentari' then 'Spesa alimentare'
  when 'spesa alimentare' then 'Spesa alimentare'
  when 'ristorante' then 'Mangiare fuori'
  when 'cena' then 'Mangiare fuori'
  when 'pranzo' then 'Mangiare fuori'
  when 'bar' then 'Mangiare fuori'
  when 'mangiare fuori' then 'Mangiare fuori'
  when 'food' then 'Mangiare fuori'
  when 'aperitivo' then 'Mangiare fuori'
  when 'trasporti' then 'Trasporti'
  when 'benzina' then 'Trasporti'
  when 'taxi' then 'Trasporti'
  when 'mezzi' then 'Trasporti'
  when 'carburante' then 'Trasporti'
  when 'treno' then 'Trasporti'
  when 'metro' then 'Trasporti'
  when 'auto' then 'Trasporti'
  when 'casa' then 'Casa'
  when 'affitto' then 'Casa'
  when 'mutuo' then 'Casa'
  when 'rent' then 'Casa'
  when 'home' then 'Casa'
  when 'bollette' then 'Bollette'
  when 'utenze' then 'Bollette'
  when 'luce' then 'Bollette'
  when 'gas' then 'Bollette'
  when 'internet' then 'Bollette'
  when 'salute' then 'Salute'
  when 'farmacia' then 'Salute'
  when 'medico' then 'Salute'
  when 'shopping' then 'Shopping'
  when 'acquisti' then 'Shopping'
  when 'abbigliamento' then 'Shopping'
  when 'vestiti' then 'Shopping'
  when 'amazon' then 'Shopping'
  when 'svago' then 'Svago'
  when 'entertainment' then 'Svago'
  when 'cinema' then 'Svago'
  when 'hobby' then 'Svago'
  when 'viaggi' then 'Viaggi'
  when 'vacanze' then 'Viaggi'
  when 'travel' then 'Viaggi'
  when 'abbonamenti' then 'Abbonamenti'
  when 'subscription' then 'Abbonamenti'
  when 'streaming' then 'Abbonamenti'
  when 'netflix' then 'Abbonamenti'
  when 'spotify' then 'Abbonamenti'
  when 'formazione' then 'Formazione'
  when 'corso' then 'Formazione'
  when 'education' then 'Formazione'
  when 'libri' then 'Formazione'
  when 'famiglia' then 'Famiglia'
  when 'bambini' then 'Famiglia'
  when 'tasse' then 'Tasse'
  when 'imposte' then 'Tasse'
  when 'f24' then 'Tasse'
  when 'agenzia entrate' then 'Tasse'
  when 'cura personale' then 'Cura personale'
  when 'beauty' then 'Cura personale'
  when 'benessere' then 'Cura personale'
  when 'regali' then 'Regali'
  when 'gift' then 'Regali'
  when 'stipendio' then 'Stipendio'
  when 'salary' then 'Stipendio'
  when 'busta paga' then 'Stipendio'
  when 'freelance' then 'Freelance'
  when 'consulenza' then 'Freelance'
  when 'attivita' then 'Attivita'
  when 'business' then 'Attivita'
  when 'azienda' then 'Attivita'
  when 'bonus' then 'Bonus'
  when 'premio' then 'Bonus'
  when 'premio produzione' then 'Bonus'
  when 'rimborso' then 'Rimborso'
  when 'refund' then 'Rimborso'
  when 'restituzione' then 'Rimborso'
  when 'investimenti' then 'Investimenti'
  when 'investment' then 'Investimenti'
  when 'dividendi' then 'Investimenti'
  when 'cedola' then 'Investimenti'
  when 'affitti' then 'Affitti'
  when 'locazione' then 'Affitti'
  when 'affitto attivo' then 'Affitti'
  when 'regalo ricevuto' then 'Regalo ricevuto'
  when 'gift income' then 'Regalo ricevuto'
  when 'pensione' then 'Pensione'
  when 'pension' then 'Pensione'
  when 'altro' then 'Altro'
  when 'uncategorized' then 'Altro'
  when 'uncategorised' then 'Altro'
  when 'income' then 'Altro'
  when 'other' then 'Altro'
  else category
end
where category is not null
  and trim(category) <> '';

update public.recurring_incomes
set category = case lower(trim(category))
  when 'stipendio' then 'Stipendio'
  when 'salary' then 'Stipendio'
  when 'busta paga' then 'Stipendio'
  when 'freelance' then 'Freelance'
  when 'consulenza' then 'Freelance'
  when 'attivita' then 'Attivita'
  when 'business' then 'Attivita'
  when 'azienda' then 'Attivita'
  when 'bonus' then 'Bonus'
  when 'premio' then 'Bonus'
  when 'premio produzione' then 'Bonus'
  when 'rimborso' then 'Rimborso'
  when 'refund' then 'Rimborso'
  when 'restituzione' then 'Rimborso'
  when 'investimenti' then 'Investimenti'
  when 'investment' then 'Investimenti'
  when 'dividendi' then 'Investimenti'
  when 'cedola' then 'Investimenti'
  when 'affitti' then 'Affitti'
  when 'rent' then 'Affitti'
  when 'locazione' then 'Affitti'
  when 'affitto attivo' then 'Affitti'
  when 'regalo ricevuto' then 'Regalo ricevuto'
  when 'gift income' then 'Regalo ricevuto'
  when 'regalo' then 'Regalo ricevuto'
  when 'pensione' then 'Pensione'
  when 'pension' then 'Pensione'
  when 'altro' then 'Altro'
  when 'income' then 'Altro'
  when 'other' then 'Altro'
  else category
end
where category is not null
  and trim(category) <> '';
